name: Release – Stable

permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Build & Test
        run: |
          pnpm compile
          pnpm test:create

      - name: Changesets publish
        uses: changesets/action@v1
        with:
          publish: pnpm -r publish --access public --provenance --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


